version: '3'
services:
  user-service:
    build: ./user-service
    ports:
      - "3001:3001"
    container_name: user-service
  product-service:
    build: ./product-service
    ports:
      - "3002:3002"
    container_name: product-service